# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindowG.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(240, 50))
        self.label_2.setMaximumSize(QtCore.QSize(240, 50))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(600, 500))
        self.label.setMaximumSize(QtCore.QSize(600, 500))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 4, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(240, 50))
        self.label_3.setMaximumSize(QtCore.QSize(240, 50))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(240, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(240, 50))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(240, 200))
        self.label_4.setMaximumSize(QtCore.QSize(240, 220))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuEdit = QtWidgets.QMenu(self.menuMenu)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSystem = QtWidgets.QMenu(self.menuMenu)
        self.menuSystem.setObjectName("menuSystem")
        self.menuHotKey = QtWidgets.QMenu(self.menuMenu)
        self.menuHotKey.setObjectName("menuHotKey")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFont_2 = QtWidgets.QAction(MainWindow)
        self.actionFont_2.setObjectName("actionFont_2")
        self.actionColor = QtWidgets.QAction(MainWindow)
        self.actionColor.setObjectName("actionColor")
        self.actionSetting = QtWidgets.QAction(MainWindow)
        self.actionSetting.setObjectName("actionSetting")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionInput = QtWidgets.QAction(MainWindow)
        self.actionInput.setObjectName("actionInput")
        self.actionView = QtWidgets.QAction(MainWindow)
        self.actionView.setObjectName("actionView")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.menuEdit.addAction(self.actionFont_2)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionColor)
        self.menuSystem.addAction(self.actionSetting)
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.actionExit)
        self.menuHotKey.addAction(self.actionView)
        self.menuHotKey.addSeparator()
        self.menuHotKey.addAction(self.actionAdd)
        self.menuHotKey.addSeparator()
        self.menuHotKey.addAction(self.actionDelete)
        self.menuHotKey.addSeparator()
        self.menuMenu.addAction(self.menuSystem.menuAction())
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.menuEdit.menuAction())
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionInput)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.menuHotKey.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "键入文本"))
        self.label.setText(_translate("MainWindow", "原视频"))
        self.label_3.setText(_translate("MainWindow", "键入文本"))
        self.pushButton.setText(_translate("MainWindow", "退出"))
        self.label_4.setText(_translate("MainWindow", "特征"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuSystem.setTitle(_translate("MainWindow", "System"))
        self.menuHotKey.setTitle(_translate("MainWindow", "HotKey"))
        self.actionFont_2.setText(_translate("MainWindow", "Font"))
        self.actionColor.setText(_translate("MainWindow", "Color"))
        self.actionSetting.setText(_translate("MainWindow", "Setting"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionInput.setText(_translate("MainWindow", "Input"))
        self.actionView.setText(_translate("MainWindow", "View"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))

